### ISSUE TITLE
3.0 Style box for 3.0 pages and Plus Formating for forums

### ISSUE THREAD

**Issue by daniel4-scratch** [ScratchFormat/scratchformat#28]
# 3.0 Style box for 3.0
I was think if there was a way to sense a 2.0 or a 3.0 page so the format box would change style to that page.

E.g if the page was 3.0, the format box would turn 3.0
![Screen Shot 2020-12-21 at 5 58 05 pm](https://user-images.githubusercontent.com/65277548/102748331-14fa7800-43b6-11eb-8c0d-9145bfedb7c1.png)
But in this case it wouldn't change so:
![Screen Shot 2020-12-21 at 5 59 52 pm](https://user-images.githubusercontent.com/65277548/102748461-5559f600-43b6-11eb-8e49-d2f6992c0d49.png)

For the 3.0 censor idea:
it has a list for urls and then depending on the url it will swap between css.
eg
```js
if (url == "https://scratch.mit.edu/project"){
document.head.innerHTML+=`<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/ScratchFormat/scratchformat/3-style.css">`
}
...
```

if you where to get acsess to the tabs you will need to add the following code into the manifest
```json
"permissions": [
    "tabs"
  ]
```

The code for the 3.0 box if you want it :)
```css
#formatter:hover {
    border: 2px solid rgb(77, 151, 255);
}

#formatter {
    background-color: white;
    border: 2px solid rgba(0, 0, 0, 0.2);
    border-radius: 8px;
    margin-bottom: 0.5em;
    padding: 2px;
    transition: all .2s ease;
}
```

# Plus Formating for Scratch Discuss

I was thinking if you would add more little tags into the discuss with musch more customization.
Like linking code files or something and they preview through the post
<sup> I feel like you wont do this one because of breaching appropriate words in the text file whithin.
